% Auto-generated by cameraCalibrator app on 27-Feb-2019
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\yliu60\Documents\GitHub\computer_vision_projects\5_camera_calibration\checker_board (1).JPG',...
    'C:\Users\yliu60\Documents\GitHub\computer_vision_projects\5_camera_calibration\checker_board (2).JPG',...
    'C:\Users\yliu60\Documents\GitHub\computer_vision_projects\5_camera_calibration\checker_board (3).JPG',...
    'C:\Users\yliu60\Documents\GitHub\computer_vision_projects\5_camera_calibration\checker_board (4).JPG',...
    'C:\Users\yliu60\Documents\GitHub\computer_vision_projects\5_camera_calibration\checker_board (5).JPG',...
    'C:\Users\yliu60\Documents\GitHub\computer_vision_projects\5_camera_calibration\checker_board (6).JPG',...
    'C:\Users\yliu60\Documents\GitHub\computer_vision_projects\5_camera_calibration\checker_board (7).JPG',...
    'C:\Users\yliu60\Documents\GitHub\computer_vision_projects\5_camera_calibration\checker_board (8).JPG',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 9.000000e-01;  % in units of 'inches'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'inches', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
